### ISSUE TITLE
App crashes when trying to exit after user logs out

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#170] opened 2017-01-13 15:02 UTC
How to reproduce -
- Run the application
- Login 
- Logout
- click on 'X' button 

Some exception is thrown

**Comment by Kolikant** [comment] 2017-01-13 16:45
Does logging out return the current user to be default user?

**Comment by kapalex** [comment] 2017-01-13 16:49
What i did was
`UserManager.logoutCurrUser();`
`Application.appUser = null;`

Anything else?

**Comment by Kolikant** [comment] 2017-01-13 17:13
Oh okay, i think i know what the problem is then, thank you for the help. Should be fixed sone

**Comment by Kolikant** [comment] 2017-01-13 17:29
okay, since the application starts by creating a default user as the app user, the implementation relies on a none null user being used.
so rather than assigning null at logout, i assigned the default user, I made this to be more intuitive by changing default user creation api. 

meaning that if no user is active, there should now be a clear assignment, that bein UserImpl.DefaultUser();

**Closed as completed by Kolikant** 2017-01-13 17:29 UTC
Labels: bug, User Management

**Comment by kapalex** [comment] 2017-01-13 17:46
Oh, yeah that's completely my bad, I forgot that's what we agreed on doing

**Comment by Kolikant** [comment] 2017-01-13 17:48
no worries :) it works now
